package com.apu.hms.models;

public enum SystemModule {
    USER_AND_STAFF_MANAGEMENT,
    PATIENT_HEALTH_RECORDS,
    APPOINTMENTS_AND_SCHEDULING,
    PRESCRIPTIONS_AND_TREATMENTS,
    BILLING_AND_PAYMENTS,
    SYSTEM_SETTINGS_AND_REPORTS
}
